[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "bf09b7cdf17f24e118521aa42868e3efed15df3f" }
freya = { git = "https://github.com/marc2332/freya", rev = "bf09b7cdf17f24e118521aa42868e3efed15df3f" }
freya-common = { git = "https://github.com/marc2332/freya", rev = "bf09b7cdf17f24e118521aa42868e3efed15df3f" }
torin = { git = "https://github.com/marc2332/freya", rev = "bf09b7cdf17f24e118521aa42868e3efed15df3f" }

dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="11c9abcf7ce731ccb4a44c52de383c090ab319af", features = ["macro", "hooks"]}
dioxus-std = { git = "https://github.com/marc2332/dioxus-std", rev = "4974f9e4e421b9036d9438ef33d4496559a76855", features = ["utils"] }

tokio = { version = "1.23.0", features = ["fs"]}
glutin = { version = "0.30.6"}
winit = "0.28.2"
skia-safe = { version = "0.63.0", features = ["gl", "textlayout", "svg"] }

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
