[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="49c5a5043a16fc82210af146c345793dd448e519", features = ["macro", "hooks"]}
freya-node-state = { git="https://github.com/marc2332/freya", rev="db4530d5bb35b1d0f84d88004165631898917745"}
freya = { git="https://github.com/marc2332/freya", rev="db4530d5bb35b1d0f84d88004165631898917745" }
freya-common = { git="https://github.com/marc2332/freya", rev="db4530d5bb35b1d0f84d88004165631898917745" }
tree-sitter-highlight = "0.20.1"
tree-sitter-rust = "0.20.3"
rfd = "0.11.0"
tokio = { version = "1.23.0", features = ["fs"]}
smallvec = "1.10.0"
ropey = "1.6.0"
glutin = { version = "0.30.6"}
winit = "0.28.2"