[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "8ddc8ce0995769009f80b6463d776ee3eded8648" }
freya = { git = "https://github.com/marc2332/freya", rev = "8ddc8ce0995769009f80b6463d776ee3eded8648" }
freya-common = { git = "https://github.com/marc2332/freya", rev = "8ddc8ce0995769009f80b6463d776ee3eded8648" }
torin = { git = "https://github.com/marc2332/freya", rev = "8ddc8ce0995769009f80b6463d776ee3eded8648" }

dioxus = { version = "0.4", features = ["macro", "hooks"] }

tokio = { version = "1.23.0", features = ["fs", "process"]}
glutin = { version = "0.30.6"}
winit = "0.28.2"
skia-safe = { version = "0.63.0", features = ["gl", "textlayout", "svg"] }

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
tower = "0.4.13"
lsp-types = "0.94.0"
async-lsp = { git = "https://github.com/marc2332/async-lsp", rev="f885653777e61b97202949120c2b60c318492252" }
futures = "0.3.28"
async-process = "1.7.0"

