[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "4f2982dd25d393a16857691246963ec69720301d" }
freya = { git = "https://github.com/marc2332/freya", rev = "4f2982dd25d393a16857691246963ec69720301d" }
freya-common = { git = "https://github.com/marc2332/freya", rev = "4f2982dd25d393a16857691246963ec69720301d" }

dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="49c5a5043a16fc82210af146c345793dd448e519", features = ["macro", "hooks"]}

tokio = { version = "1.23.0", features = ["fs"]}
glutin = { version = "0.30.6"}
winit = "0.28.2"

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"