[package]
name = "valin"
version = "0.0.3"
edition = "2021"

[patch.crates-io]
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", rev = "57ab3fa972c6d4a7acc25e82a0aafc3ff9e63403" }

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "1b1eb3ea7179dfc3b1840f9ba306c4e58d7ca4b1" }
freya = { git = "https://github.com/marc2332/freya", rev = "1b1eb3ea7179dfc3b1840f9ba306c4e58d7ca4b1" }
freya-hooks = { git = "https://github.com/marc2332/freya", rev = "1b1eb3ea7179dfc3b1840f9ba306c4e58d7ca4b1" }

dioxus-radio = "0.2.4"
dioxus = "0.5"
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", rev = "57ab3fa972c6d4a7acc25e82a0aafc3ff9e63403", features = ["clipboard", "timing"] }

tokio = { version = "1.33.0", features = ["fs", "process"]}
winit = "0.29.9"
skia-safe = { version = "0.72.0", features = ["gl", "textlayout", "svg"] }

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
tower = "0.4.13"
lsp-types = "0.94.0"
async-lsp = { git = "https://github.com/marc2332/async-lsp", rev="f885653777e61b97202949120c2b60c318492252" }
futures = "0.3.28"
tokio-util = { version = "0.7.11", features = ["compat"] }
clap = { version = "4.5.4", features = ["derive"]}
async-trait = "0.1.80"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[profile.release]
lto = true
