[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "e254d8254afdb7a56ae623d6ee133405e88d9c48" }
freya = { git = "https://github.com/marc2332/freya", rev = "e254d8254afdb7a56ae623d6ee133405e88d9c48" }
freya-common = { git = "https://github.com/marc2332/freya", rev = "e254d8254afdb7a56ae623d6ee133405e88d9c48" }
torin = { git = "https://github.com/marc2332/freya", rev = "e254d8254afdb7a56ae623d6ee133405e88d9c48" }

dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="b264211cc2685232426317d3055046838047d3db", features = ["macro", "hooks"]}

tokio = { version = "1.23.0", features = ["fs"]}
glutin = { version = "0.30.6"}
winit = "0.28.2"

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"