[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "66e9eb9aef7a5d8a43c61e7e6c5b5ffc3ba2f648" }
freya = { git = "https://github.com/marc2332/freya", rev = "66e9eb9aef7a5d8a43c61e7e6c5b5ffc3ba2f648" }
freya-common = { git = "https://github.com/marc2332/freya", rev = "66e9eb9aef7a5d8a43c61e7e6c5b5ffc3ba2f648" }
torin = { git = "https://github.com/marc2332/freya", rev = "66e9eb9aef7a5d8a43c61e7e6c5b5ffc3ba2f648" }

dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="0527cff3a59ba3176f7510a7234c5977ce1b17d7", features = ["macro", "hooks"]}

tokio = { version = "1.23.0", features = ["fs"]}
glutin = { version = "0.30.6"}
winit = "0.28.2"

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"