[package]
name = "freya-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { git = "https://github.com/marc2332/freya", rev = "4c32259e9f3974fc2b96c36651ab8df20a273be0" }
freya = { git = "https://github.com/marc2332/freya", rev = "4c32259e9f3974fc2b96c36651ab8df20a273be0" }
freya-common = { git = "https://github.com/marc2332/freya", rev = "4c32259e9f3974fc2b96c36651ab8df20a273be0" }
torin = { git = "https://github.com/marc2332/freya", rev = "4c32259e9f3974fc2b96c36651ab8df20a273be0" }
freya-hooks = { git = "https://github.com/marc2332/freya", rev = "4c32259e9f3974fc2b96c36651ab8df20a273be0" }

dioxus-radio = "0.2"
dioxus = "0.5"
dioxus-sdk = { version = "0.5", features = ["clipboard"]}

tokio = { version = "1.33.0", features = ["fs", "process"]}
glutin = { version = "0.31.2"}
winit = "0.29.9"
skia-safe = { version = "0.72.0", features = ["gl", "textlayout", "svg"] }

ropey = "1.6.0"
smallvec = "1.10.0"
uuid = { version =  "1.2.2", features = ["v4"]}
rfd = "0.11.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
tower = "0.4.13"
lsp-types = "0.94.0"
async-lsp = { git = "https://github.com/marc2332/async-lsp", rev="f885653777e61b97202949120c2b60c318492252" }
futures = "0.3.28"
async-process = "1.7.0"
debounced = "0.1.0"
futures-channel = "0.3.28"

